### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by BFergerson** [src-d/engine#104]
I accidentally typed the command `srcd parse drivers install list` instead of `srcd parse drivers list` and received error:

```
INFO[0000] installing driver                             language=list version=latest
ERRO[0000] unable to install version latest of list driver: rpc error: code = Unknown desc = can't install list driver: rpc error: code = Unknown desc = errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

`authentication required` is an odd error for this mistaken command.

**Comment by smola** [comment]
Thanks for the report @BFergerson!
I filed an issue for bblfsh/bblfshd, where we'll need to fix this: https://github.com/bblfsh/bblfshd/issues/207

**Comment by bzz** [comment]
bblfsh/bblfshd#207 was fixed and will be included in next release.

**Comment by carlosms** [comment]
bblfsh 2.10.0 solves the error message when you use `bblfshctl`, but for `srcd parse drivers install list` we are still showing the exact same error as before. We'll need to make changes on our side.

**Comment by carlosms** [comment]
This issue is not valid anymore, we have removed driver management commands in #188.
